### ISSUE TITLE
Note dataset creation and operation difficulties

### ISSUE THREAD

**Issue by endremborza** [sscu-budapest/sscutils#21]
Take notes right here if something unexpected non-intuitive is encountered during creation and/or operation of datasets.

**Comment by papsebestyen** [comment]
Az oszlopok átnevezése az `update_data.py` fájlban sok időt vett igénybe.

**Comment by papsebestyen** [comment]
Sokszor volt eltérés az alap csv fájlok és a namespace oszlopnevek között, főleg azért mert a namespaceben már egyszerűbb neveket akartam használni. Ezeknél az eltéréseknél azonban nehéz volt visszakövetni, hogy pontosan hol van eltérés.
